//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Soper
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Опертор.
    /// </summary>
    // *** Start programmer edit section *** (Опертор CustomAttributes)

    // *** End programmer edit section *** (Опертор CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОперторE", new string[] {
            "ID as \'ID\'",
            "КодДоступа as \'Код доступа\'",
            "ФИО as \'ФИО\'"})]
    [View("ОперторL", new string[] {
            "ID as \'ID\'",
            "КодДоступа as \'Код доступа\'",
            "ФИО as \'ФИО\'"})]
    public class Опертор : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fФИО;
        
        private int fКодДоступа;
        
        // *** Start programmer edit section *** (Опертор CustomMembers)

        // *** End programmer edit section *** (Опертор CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Опертор.ID CustomAttributes)

        // *** End programmer edit section *** (Опертор.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Опертор.ID Get start)

                // *** End programmer edit section *** (Опертор.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Опертор.ID Get end)

                // *** End programmer edit section *** (Опертор.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Опертор.ID Set start)

                // *** End programmer edit section *** (Опертор.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Опертор.ID Set end)

                // *** End programmer edit section *** (Опертор.ID Set end)
            }
        }
        
        /// <summary>
        /// КодДоступа.
        /// </summary>
        // *** Start programmer edit section *** (Опертор.КодДоступа CustomAttributes)

        // *** End programmer edit section *** (Опертор.КодДоступа CustomAttributes)
        public virtual int КодДоступа
        {
            get
            {
                // *** Start programmer edit section *** (Опертор.КодДоступа Get start)

                // *** End programmer edit section *** (Опертор.КодДоступа Get start)
                int result = this.fКодДоступа;
                // *** Start programmer edit section *** (Опертор.КодДоступа Get end)

                // *** End programmer edit section *** (Опертор.КодДоступа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Опертор.КодДоступа Set start)

                // *** End programmer edit section *** (Опертор.КодДоступа Set start)
                this.fКодДоступа = value;
                // *** Start programmer edit section *** (Опертор.КодДоступа Set end)

                // *** End programmer edit section *** (Опертор.КодДоступа Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Опертор.ФИО CustomAttributes)

        // *** End programmer edit section *** (Опертор.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Опертор.ФИО Get start)

                // *** End programmer edit section *** (Опертор.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Опертор.ФИО Get end)

                // *** End programmer edit section *** (Опертор.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Опертор.ФИО Set start)

                // *** End programmer edit section *** (Опертор.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Опертор.ФИО Set end)

                // *** End programmer edit section *** (Опертор.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОперторE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОперторE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОперторE", typeof(IIS.Soper.Опертор));
                }
            }
            
            /// <summary>
            /// "ОперторL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОперторL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОперторL", typeof(IIS.Soper.Опертор));
                }
            }
        }
    }
}
