//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Soper
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверка.
    /// </summary>
    // *** Start programmer edit section *** (Проверка CustomAttributes)

    // *** End programmer edit section *** (Проверка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроверкаE", new string[] {
            "Опертор as \'Опертор\'",
            "Опертор.ID as \'ID оператора\'",
            "Опертор.КодДоступа as \'Код доступа\'",
            "Опертор.ФИО as \'ФИО\'",
            "Терминал as \'Терминал\'",
            "Терминал.Номер as \'Номер\'",
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "ЛентаПечати as \'Лента печати\'"}, Hidden=new string[] {
            "Опертор.ФИО",
            "Терминал.Номер"})]
    [MasterViewDefineAttribute("ПроверкаE", "Опертор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПроверкаE", "Терминал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("ПроверкаL", new string[] {
            "Терминал.Номер as \'Номер\'",
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "ЛентаПечати as \'Лента печати\'",
            "Опертор.ФИО as \'ФИО\'"})]
    public class Проверка : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private string fВремя;
        
        private bool fЛентаПечати;
        
        private IIS.Soper.Терминал fТерминал;
        
        private IIS.Soper.Опертор fОпертор;
        
        // *** Start programmer edit section *** (Проверка CustomMembers)

        // *** End programmer edit section *** (Проверка CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Проверка.Время CustomAttributes)

        // *** End programmer edit section *** (Проверка.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (Проверка.Время Get start)

                // *** End programmer edit section *** (Проверка.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (Проверка.Время Get end)

                // *** End programmer edit section *** (Проверка.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверка.Время Set start)

                // *** End programmer edit section *** (Проверка.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Проверка.Время Set end)

                // *** End programmer edit section *** (Проверка.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Проверка.Дата CustomAttributes)

        // *** End programmer edit section *** (Проверка.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Проверка.Дата Get start)

                // *** End programmer edit section *** (Проверка.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Проверка.Дата Get end)

                // *** End programmer edit section *** (Проверка.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверка.Дата Set start)

                // *** End programmer edit section *** (Проверка.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Проверка.Дата Set end)

                // *** End programmer edit section *** (Проверка.Дата Set end)
            }
        }
        
        /// <summary>
        /// ЛентаПечати.
        /// </summary>
        // *** Start programmer edit section *** (Проверка.ЛентаПечати CustomAttributes)

        // *** End programmer edit section *** (Проверка.ЛентаПечати CustomAttributes)
        public virtual bool ЛентаПечати
        {
            get
            {
                // *** Start programmer edit section *** (Проверка.ЛентаПечати Get start)

                // *** End programmer edit section *** (Проверка.ЛентаПечати Get start)
                bool result = this.fЛентаПечати;
                // *** Start programmer edit section *** (Проверка.ЛентаПечати Get end)

                // *** End programmer edit section *** (Проверка.ЛентаПечати Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверка.ЛентаПечати Set start)

                // *** End programmer edit section *** (Проверка.ЛентаПечати Set start)
                this.fЛентаПечати = value;
                // *** Start programmer edit section *** (Проверка.ЛентаПечати Set end)

                // *** End programmer edit section *** (Проверка.ЛентаПечати Set end)
            }
        }
        
        /// <summary>
        /// Проверка.
        /// </summary>
        // *** Start programmer edit section *** (Проверка.Опертор CustomAttributes)

        // *** End programmer edit section *** (Проверка.Опертор CustomAttributes)
        [PropertyStorage(new string[] {
                "Опертор"})]
        [NotNull()]
        public virtual IIS.Soper.Опертор Опертор
        {
            get
            {
                // *** Start programmer edit section *** (Проверка.Опертор Get start)

                // *** End programmer edit section *** (Проверка.Опертор Get start)
                IIS.Soper.Опертор result = this.fОпертор;
                // *** Start programmer edit section *** (Проверка.Опертор Get end)

                // *** End programmer edit section *** (Проверка.Опертор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверка.Опертор Set start)

                // *** End programmer edit section *** (Проверка.Опертор Set start)
                this.fОпертор = value;
                // *** Start programmer edit section *** (Проверка.Опертор Set end)

                // *** End programmer edit section *** (Проверка.Опертор Set end)
            }
        }
        
        /// <summary>
        /// Проверка.
        /// </summary>
        // *** Start programmer edit section *** (Проверка.Терминал CustomAttributes)

        // *** End programmer edit section *** (Проверка.Терминал CustomAttributes)
        [PropertyStorage(new string[] {
                "Терминал"})]
        [NotNull()]
        public virtual IIS.Soper.Терминал Терминал
        {
            get
            {
                // *** Start programmer edit section *** (Проверка.Терминал Get start)

                // *** End programmer edit section *** (Проверка.Терминал Get start)
                IIS.Soper.Терминал result = this.fТерминал;
                // *** Start programmer edit section *** (Проверка.Терминал Get end)

                // *** End programmer edit section *** (Проверка.Терминал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверка.Терминал Set start)

                // *** End programmer edit section *** (Проверка.Терминал Set start)
                this.fТерминал = value;
                // *** Start programmer edit section *** (Проверка.Терминал Set end)

                // *** End programmer edit section *** (Проверка.Терминал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроверкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаE", typeof(IIS.Soper.Проверка));
                }
            }
            
            /// <summary>
            /// "ПроверкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаL", typeof(IIS.Soper.Проверка));
                }
            }
        }
    }
}
